name: Other
description: Anything else not already covered by other categories.
title: "[OTHER] PLEASE REPLACE THIS TEXT WITH A SUMMARY OF YOUR ISSUE..."
labels: ["other"]
assignees:
  - celenity
  - celenityy
body:
  - type: textarea
    id: reason
    attributes:
      label: Please explain your inquiry.
    validations:
      required: true
